#!/bin/bash
echo "ER:LC Discord Bot - Setup Guide"
echo "================================"
echo ""
echo "1. Copy .env.example to .env"
echo "2. Fill in your bot token and other required values"
echo "3. Run: npm install"
echo "4. Run: npm run build"
echo "5. Run: npm start"
echo ""
echo "To run in development mode:"
echo "npm run dev"
echo ""
echo "For more information, visit: https://github.com/TokaV1/erlc-discord-bot"
